### ISSUE TITLE
How to make single prediction

### ISSUE THREAD

**Issue by Wheele9** [nlintz/TensorFlow-Tutorials#13]
Hi

I am new to tensorflow, and I am stuck at your logistic_expression example.
I trained and saved the model, restored it, but I am unable to use it. Can you help me with that?
I tried:

print (sess.run(predict_op, feed_dict={X: teX[66], Y: teY[66]}))
I am expecting a 6 here as output (or a number at least :D) but I got an error:

ValueError: Cannot feed value of shape (784,) for Tensor 'Placeholder:0', which has shape '(?, 784)'

**Comment by Waateur** [comment]
Hello, 
It's feels to me that you did you predict_op using a batch input  size :  `( None,  784 )` . 
But the data in teX are` (784,)` . You should reshape them in order to be `( 1 , 784 )` . 
You can use reshape for a numpy.ndarray or a list comprehension  for a float list  something like : 
`[ [x] for x in teX ]`

Hope it helped.

**Comment by Wheele9** [comment]
Hello
I guess I undestood the problem thanks! I solved it like that:
```
newtx=[ [x] for x in teX ]
newty=[[y] for y in teY]
print (sess.run(prediction, feed_dict={X: newtx[nr], Y: newty[nr]}))
```

**Comment by nlintz** [comment]
You can actually run the predict op without passing in Y:teY since Y isn't part of the predict_op graph. You can just run sess.run(predict_op, feed_dict={X: teX}))

**Comment by Wheele9** [comment]
Yeah i figured that out, thanks!
